apiVersion: apps/v1
kind: Deployment
metadata:
  name: listener-app-k8
  labels:
    app: listener-app-k8
spec:
  replicas: 1
  selector:
    matchLabels:
      app: listener-app-k8
  template:
    metadata:
      labels:
        app: listener-app-k8
    spec:
      containers:
        - name: listener-app-k8
          imagePullPolicy: Never
          image: listener-app-image
          readinessProbe:
            failureThreshold: 0 
            httpGet:
              path: /health
              port: 8090
              scheme: HTTP
            initialDelaySeconds: 15
            periodSeconds: 15
            timeoutSeconds: 15
          resources:
            limits:
              cpu: 1000m
              memory: 1Gi
            requests:
              cpu: 500m
              memory: 1Gi
