apiVersion: apps/v1
kind: Deployment
metadata:
  name: listener-app-k8
  labels:
    app: listener-app-k8
spec:
  replicas: 0
  selector:
    matchLabels:
      app: listener-app-k8
  template:
    metadata:
      labels:
        app: listener-app-k8
    spec:
      containers:
        - name: listener-app-k8
          imagePullPolicy: Never
          image: listener-app-image
